### ISSUE TITLE
Incorrect areal proportion returned when other columns in spatial_grid

### ISSUE THREAD

**Issue by jaseeverett** [emlab-ucsb/spatialgridr#13]
This is both a bug and a feature request....

BUG: When you use `get_data_in_grid` and your `spatial_grid` data frame has other data already in it, the function returns the incorrect data (usually the area of the planning unit rather than the area of the intersection).  See the reprex below for details, modified from the example code.

REQUEST: `spatial_grid` should be able to have other data (columns) already in it. For example when I use this code for multiple shape files, I will pipe the `spatial_grid` from one to the next, so each time the `spatial_grid` goes back into the  `get_data_in_grid` it has additional columns. That way I don't have to continually bind_cols or do joins to compile all the data. A quick solution would be for `get_data_in_grid` to remove and store all non-geometry columns at the top of the code, and then add them all back in before returning the data to the user. That way the user gets their data and exisiting code isn't confused by the additional columns (However it is still a problem that the Bug above occurs because something is obviously not working correctly. Perhaps you are assuming a column position/index rather than a column name?). 

```

# ridges data for area of Pacific
ridges <- system.file("extdata", "ridges.rds", package = "spatialgridr") |> readRDS()

# an area of interest, in this case Samoa's Exclusive Economic Zone
samoa_eez <- system.file("extdata", "samoa_eez.rds", package = "spatialgridr") |> readRDS()

# You need a suitable projection for your area of interest, https://projectionwizard.org is useful for this purpose. For spatial planning, equal area projections are normally best.
samoa_projection <- '+proj=laea +lon_0=-172.5 +lat_0=0 +datum=WGS84 +units=m +no_defs'

# Create a planning grid with 5km sized planning units
planning_grid <- get_grid(area_polygon = samoa_eez, projection_crs = samoa_projection, resolution = 5000, option = "sf_hex") %>% 
  dplyr::mutate(Area = as.numeric(sf::st_area(.)))


# INCORRECT - Has extra data column and returns area of planning unit, not intersection.
ridges_sf <- get_data_in_grid(spatial_grid = planning_grid, dat = ridges, apply_cutoff = FALSE, name = "Ridges")

# CORRECT - Extra columns are removed via `select` and therefore returns intersection proportion
ridges_sf2 <- get_data_in_grid(spatial_grid = planning_grid %>% dplyr::select(geometry), dat = ridges, apply_cutoff = FALSE, name = "Ridges")
```

**Comment by jflowernet** [comment]
Thanks for catching that. I'll get a fix pushed tomorrow.
