### ISSUE TITLE
Return proportion coverage of polygons

### ISSUE THREAD

**Issue by jaseeverett** [emlab-ucsb/spatialgridr#2]
When converting from binary sf polygons to planning units, it would be good to have the option to return the proportion of coverage (rather than just a binary for intersection). In that way, the user can choose their own cutoff for whether a polygon should be added to a particular planning unit. We for example often use 50%. Otherwise use more/less.

We have some code for this which I can add here.

**Comment by jaseeverett** [comment]
Option added in #4 and #5 but only works when the argument `sf_col_layer_names` is used. There will be instances when the user has a single feature in an sf object and doesn't need to name the column, or alternatively, there is only the `geometry` column so it will be impossible to return the proportion coverage.

It would be good to have `return_cov_frac = TRUE` working for both use cases

**Comment by jaseeverett** [comment]
As a 3rd use case. I am working on the IUCN seagrass data which has heaps of data columns, but I don't want to group by any of them. I just want to get the proportion of seagrass coverage for all species for any PU.

**Comment by jflowernet** [comment]
The PR should fix this, but I'll leave this open till you confirm Jase
